### PR TITLE
Fix upload for pull request builds

### PR DESCRIPTION
**Pull request by karottenreibe**
**don't follow symlinks when searching for files**
This may cause unintended behaviour and be a security problem.

**fix: root directory for search with pattern is one folder too far up**
This may cause permission exceptions when the plugin incorrectly searches folders that it has no access to

_I verified that this was broken before and now works manually against our ADO instance_

**fix: revision used for upload from pull request builds is incorrect**
We read BUILD_SOURCEVERSION but this is the simulated merge commit for the PR, which TS never sees. Instead there's SYSTEM_PULLREQUEST_SOURCECOMMITID that holds the tip of the source branch.

_I verified that the commit in that variable is correct in our pipelines for PR builds_

### CODE REVIEW

**Review by rottkit — CHANGES_REQUESTED** [review]
Thanks for the changes,
- Looks fine on the implementation side :-) 
- Do you have a specific test setup (e.g. in our Azure DevOps repository) that I can easily use to test the changes (in best case before/after)?
- I think we should reconsider the settings of prettier. To me those seem to be inconsistent with those used for Teamscale code. As a prominent example all single ticks are now quotes, which is not in-line with our TypeScript coding guidelines. This also shows up in TSLint analysis, when including the the "reportUploadTask" folder which is not the case both on master and on this branch (do not remember the reasons why we excluded this directory).

**Comment by rottkit** [comment]
I just read that you have manually tested the new behaviour. So leave out the second point of my review, if you do not think it brings additional benefit if I test it again. 🙂

**Comment by karottenreibe** [comment]
good point, I didn't know we customize prettier (early on I had heard we use the defaults). I copied our .prettierrc and reformatted the file

**Comment by rottkit** [comment]
As discussed, did not test but from a code perspective this is fine. Thanks a lot for the fix 🙂

**Pull request merged**
